# Server bind address
bind = "0.0.0.0:8000"

# Forward headers to upstream services.
forward_headers = []

# Jaeger
[jaeger]
agent_endpoint = "127.0.0.1:6831"
service_name = "graphgate"

#######################################################
## Services
#######################################################

[[services]]
name = "accounts"               # Service name
addr = "127.0.0.1:4001"         # Service address
query_path = "/"                # GraphQL query endpoint, Default: /
subscribe_path = "/"            # GraphQL subscription endpoint, Default: /
introspection_path = "/"        # GraphQL introspection path, Default: /#
websocket_path = "/"            # Endpoint to be used for graphql-transport-ws,
                                # may be different from path used for subscriptions or queries
                                # defaults to query path otherwise /

[[services]]
name = "reviews"
addr = "127.0.0.1:4002"


[[services]]
name = "products"
addr = "127.0.0.1:4003"


[[services]]
name = "inventory"
addr = "127.0.0.1:4004"
